// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK0UK6p60oPrMCFP9gOpHL0y4MdQ05A1o',
    appId: '1:967428610533:web:0d8964bbf9a7a2d545770c',
    messagingSenderId: '967428610533',
    projectId: 'fir-9481a',
    authDomain: 'fir-9481a.firebaseapp.com',
    storageBucket: 'fir-9481a.firebasestorage.app',
    measurementId: 'G-XDGX9FPKSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABbrhci698t6eRMCScWWaYeZo-0wSEm0I',
    appId: '1:967428610533:android:369a95918517214345770c',
    messagingSenderId: '967428610533',
    projectId: 'fir-9481a',
    storageBucket: 'fir-9481a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCms1l9g9_f754KT2h3dGsIWG26hmkBCGk',
    appId: '1:967428610533:ios:85fdb4130416edfb45770c',
    messagingSenderId: '967428610533',
    projectId: 'fir-9481a',
    storageBucket: 'fir-9481a.firebasestorage.app',
    androidClientId: '967428610533-38tqadeihvhc7652f3p6o7n2l0vb88e4.apps.googleusercontent.com',
    iosClientId: '967428610533-940s5op7e1i0rf57tmmdlhtrj8j3p0kk.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
